import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}','./components/**/*.{js,ts,jsx,tsx,mdx}','./app/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        display: ['Syne','sans-serif'], body: ['DM Sans','sans-serif'],
        mono: ['JetBrains Mono','monospace'], sans: ['DM Sans','sans-serif'],
      },
      colors: {
        void: 'var(--bg-void)',
        deep: 'var(--bg-deep)',
        surface: 'var(--bg-surface)',
        elevated: 'var(--bg-elevated)',
        overlay: 'var(--bg-overlay)',
        teal: {
          DEFAULT: 'var(--accent-primary)',
          dim: 'var(--accent-primary-dim)',
          bright: 'var(--accent-primary-bright)',
          50: 'var(--accent-primary-bg)',
          100: 'var(--accent-primary-bg)',
          200: 'var(--accent-primary-border)',
        },
        amber: { DEFAULT: 'var(--accent-secondary)', dim: 'var(--accent-secondary-dim)' },
        violet: { DEFAULT: 'var(--accent-tertiary)', dim: 'var(--accent-tertiary-dim)' },
        track: {
          frontend: 'var(--track-frontend)',
          backend: 'var(--track-backend)',
          fullstack: 'var(--track-fullstack)',
          python: 'var(--track-python)',
          uiux: 'var(--track-uiux)',
          qa: 'var(--track-qa)',
          data: 'var(--track-data)',
          datascience: 'var(--track-datascience)',
          devops: 'var(--track-devops)',
          cyber: 'var(--track-cyber)',
          mobile: 'var(--track-mobile)',
          video: 'var(--track-video)',
          youtube: 'var(--track-youtube)',
          marketing: 'var(--track-marketing)',
          ai: 'var(--track-ai)',
          nocode: 'var(--track-nocode)',
          writing: 'var(--track-writing)',
        },
        border: {
          subtle: 'var(--border-subtle)',
          default: 'var(--border-default)',
          active: 'var(--border-active)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverse: 'var(--text-inverse)',
        },
      },
      borderRadius: { xs: '4px', sm: '6px', md: '10px', lg: '16px', xl: '24px', '2xl': '32px' },
      boxShadow: {
        card: 'var(--shadow-card)',
        raised: 'var(--shadow-raised)',
        modal: '0 10px 25px -5px rgba(0, 0, 0, 0.05), 0 8px 10px -6px rgba(0, 0, 0, 0.05)',
        'glow-teal': 'var(--shadow-glow-teal)',
        'glow-amber': '0 0 8px rgba(217,119,6,0.1)',
      },
      backgroundImage: {
        'gradient-hero': 'linear-gradient(135deg, #080B10 0%, #0D1117 50%, #0A1628 100%)',
        'gradient-text': 'linear-gradient(92deg, #00D4AA 0%, #61DAFB 45%, #A78BFA 100%)',
        'gradient-accent': 'linear-gradient(90deg, #00D4AA, #A78BFA)',
        'gradient-warm': 'linear-gradient(135deg, #F0A500, #FC8181)',
        'grid-pattern': 'linear-gradient(rgba(0,212,170,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(0,212,170,0.03) 1px, transparent 1px)',
        'dot-pattern': 'radial-gradient(rgba(0,212,170,0.12) 1px, transparent 1px)',
      },
      backgroundSize: { grid: '40px 40px', dot: '24px 24px' },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        'scale-in': 'scaleIn 0.3s cubic-bezier(0.34,1.56,0.64,1) forwards',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'progress-fill': 'progressFill 1s ease-out forwards',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        glowPulse: { '0%,100%': { boxShadow: '0 0 16px rgba(0,212,170,0.3)' }, '50%': { boxShadow: '0 0 32px rgba(0,212,170,0.6)' } },
        float: { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-10px)' } },
        progressFill: { from: { width: '0%' }, to: { width: 'var(--progress-width, 0%)' } },
      },
      transitionTimingFunction: { spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)', smooth: 'cubic-bezier(0.4, 0, 0.2, 1)' },
      maxWidth: { content: '70ch', site: '1320px' },
      fontSize: {
        'display-md': ['clamp(1.75rem, 3.5vw, 2.75rem)', { lineHeight: '1.2' }],
      },
    },
  },
  plugins: [],
}
export default config
