import type { Project, Resource } from './tracks'
import type { QuizQuestion } from './guided-path'

/** Phase 3A content. Uses the existing Track/Resource/Project/Quiz/guided-path system. */

export const AI_RESOURCE_EXTENSIONS: Record<string, Resource[]> = {
  'ai-foundations': [
    { id: 'ai-f8', title: 'OpenAI Academy — AI Foundations', description: 'Free, self-paced AI foundation course covering LLMs, prompting, context, output review, and responsible use.', url: 'https://academy.openai.com/public/courses/ai-foundations-juzjs?autoEnroll=true', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-f9', title: 'Microsoft Learn — Introduction to Generative AI', description: 'Beginner module covering generative AI, LLMs, model comparison, critical thinking, responsible use, and assessment.', url: 'https://learn.microsoft.com/en-us/training/modules/intro-generative-ai-explore-basics/', type: 'docs', free: true, source: 'Microsoft Learn' },
    { id: 'ai-f10', title: 'Microsoft — Generative AI for Beginners', description: 'Free 18-lesson series covering LLMs, model comparison, responsible AI, prompting, RAG, security, agents, and application lifecycle.', url: 'https://www.youtube.com/watch?v=k7HaeJs-N-o', type: 'video', free: true, source: 'Microsoft Developer' },
    { id: 'ai-f11', title: '3Blue1Brown — Neural Networks', description: 'Visual explanation of neural networks for learners who want a deeper conceptual model of how modern AI learns patterns.', url: 'https://www.youtube.com/watch?v=aircAruvnKk', type: 'video', free: true, source: '3Blue1Brown' },
  ],
  'ai-work': [
    { id: 'ai-w4', title: 'OpenAI Academy — Getting Started With ChatGPT', description: 'Official practical guidance for prompting, files, search, image creation, projects, and repeatable workflows.', url: 'https://openai.com/academy/getting-started/', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-w5', title: 'OpenAI Academy — Using ChatGPT', description: 'Practical guidance for moving beyond basic chat into files, search, projects, skills, and repeatable work.', url: 'https://openai.com/academy/using-chatgpt/', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-w6', title: 'Microsoft Learn — Unlock Productivity With Generative AI', description: 'Free business-focused module covering productivity use cases, responsible use, security, and AI adoption.', url: 'https://learn.microsoft.com/en-us/training/modules/generative-ai-productivity/', type: 'docs', free: true, source: 'Microsoft Learn' },
  ],
  'ai-research': [
    { id: 'ai-r3', title: 'OpenAI Academy — AI Fundamentals', description: 'Understand how AI systems work, their limitations, and responsible use when evaluating outputs.', url: 'https://openai.com/academy/what-is-ai/', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-r4', title: 'Google Scholar', description: 'Free academic search engine for locating research papers and tracing claims toward primary evidence.', url: 'https://scholar.google.com/', type: 'tool', free: true, source: 'Google Scholar' },
    { id: 'ai-r5', title: 'Microsoft Learn — AI and Search Training', description: 'Free Microsoft training catalogue containing current search, AI, and research-oriented learning modules.', url: 'https://learn.microsoft.com/en-us/training/', type: 'docs', free: true, source: 'Microsoft Learn' },
  ],
  'ai-content': [
    { id: 'ai-c3', title: 'OpenAI Academy — Applied AI Foundations', description: 'Learn to turn recurring tasks into repeatable AI workflows with explicit review points.', url: 'https://academy.openai.com/', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-c4', title: 'Canva Design School', description: 'Free design education for visual communication and composition; useful grounding for AI-assisted creative work.', url: 'https://www.canva.com/designschool/', type: 'docs', free: true, source: 'Canva' },
    { id: 'ai-c5', title: 'Microsoft — Generative AI for Beginners', description: 'Free series covering prompting, image generation, UX for AI applications, security, and responsible AI.', url: 'https://www.youtube.com/watch?v=k7HaeJs-N-o', type: 'video', free: true, source: 'Microsoft Developer' },
  ],
  'ai-youtube': [
    { id: 'ai-y3', title: 'YouTube Creator Academy — Analytics', description: 'Official guidance on impressions, CTR, watch time, retention, reach, and audience reports.', url: 'https://creatoracademy.youtube.com/page/lesson/using-analytics', type: 'docs', free: true, source: 'YouTube' },
    { id: 'ai-y4', title: 'YouTube Monetization Policies', description: 'Official policy covering original value, reused content, and inauthentic mass-produced content.', url: 'https://support.google.com/youtube/answer/1311392', type: 'docs', free: true, source: 'YouTube' },
    { id: 'ai-y5', title: 'YouTube — Disclosing Use of Generative AI', description: 'Official requirements and examples for disclosing realistic AI-generated or meaningfully altered content.', url: 'https://support.google.com/youtube/answer/14328491', type: 'docs', free: true, source: 'YouTube' },
    { id: 'ai-y6', title: 'Microsoft — Generative AI for Beginners', description: 'Free video series covering prompting, image generation, UX, RAG, security, and agents.', url: 'https://www.youtube.com/watch?v=k7HaeJs-N-o', type: 'video', free: true, source: 'Microsoft Developer' },
  ],
  'ai-software-development': [
    { id: 'ai-s4', title: 'GitHub Copilot Documentation', description: 'Official documentation for AI-assisted coding, code review, and agentic development workflows.', url: 'https://docs.github.com/en/copilot', type: 'docs', free: true, source: 'GitHub' },
    { id: 'ai-s5', title: 'OpenAI Academy — Codex', description: 'Official guidance for AI-assisted coding tasks and workflows with emphasis on delegation and review.', url: 'https://openai.com/academy/codex/', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-s6', title: 'Anthropic — Build With Claude', description: 'Official API and prompting guidance covering model choice, tools, and application development.', url: 'https://www.anthropic.com/learn/build-with-claude', type: 'docs', free: true, source: 'Anthropic' },
    { id: 'ai-s7', title: 'Microsoft — Generative AI for Beginners', description: 'Free series covering application lifecycle, function calling, RAG, security, agents, and model fundamentals.', url: 'https://www.youtube.com/watch?v=k7HaeJs-N-o', type: 'video', free: true, source: 'Microsoft Developer' },
  ],
  'ai-automation': [
    { id: 'ai-a4', title: 'n8n Documentation', description: 'Official documentation for triggers, nodes, integrations, credentials, and workflow automation.', url: 'https://docs.n8n.io/', type: 'docs', free: true, source: 'n8n' },
    { id: 'ai-a5', title: 'n8n Courses', description: 'Free structured learning resources for building and debugging automation workflows.', url: 'https://docs.n8n.io/courses/', type: 'docs', free: true, source: 'n8n' },
    { id: 'ai-a6', title: 'Microsoft Learn — Generative AI and Agents', description: 'Free module introducing LLMs, prompts, agents, and applied generative AI concepts for workflows.', url: 'https://learn.microsoft.com/en-us/training/modules/fundamentals-generative-ai/', type: 'docs', free: true, source: 'Microsoft Learn' },
  ],
  'ai-agents': [
    { id: 'ai-ag4', title: 'OpenAI Academy — Agents & Workflows', description: 'Free course material on context, outputs, boundaries, review, and repeatable agent workflows.', url: 'https://academy.openai.com/', type: 'docs', free: true, source: 'OpenAI Academy' },
    { id: 'ai-ag5', title: 'Microsoft Learn — Generative AI and Agents', description: 'Beginner module explaining LLMs, prompts, agents, and an applied exercise with knowledge check.', url: 'https://learn.microsoft.com/en-us/training/modules/fundamentals-generative-ai/', type: 'docs', free: true, source: 'Microsoft Learn' },
    { id: 'ai-ag6', title: 'Microsoft Learn — Get Started With Generative AI and Agents', description: 'Hands-on module covering model selection, agent creation, testing, and agent calls from code.', url: 'https://learn.microsoft.com/en-us/training/modules/get-started-with-generative-ai-and-agents/', type: 'docs', free: true, source: 'Microsoft Learn' },
    { id: 'ai-ag7', title: 'Anthropic — Build With Claude', description: 'Official guidance for model selection, tools, prompts, APIs, and agentic development.', url: 'https://www.anthropic.com/learn/build-with-claude', type: 'docs', free: true, source: 'Anthropic' },
  ],
  'ai-engineering': [
    { id: 'ai-e5', title: 'OpenAI API Documentation', description: 'Official API reference for models, structured outputs, tools, embeddings, and application patterns.', url: 'https://platform.openai.com/docs', type: 'docs', free: true, source: 'OpenAI' },
    { id: 'ai-e6', title: 'Anthropic — Build With Claude', description: 'Official developer guidance for Claude APIs, prompting, tools, model selection, and applications.', url: 'https://www.anthropic.com/learn/build-with-claude', type: 'docs', free: true, source: 'Anthropic' },
    { id: 'ai-e7', title: 'Microsoft — Generative AI for Beginners', description: 'Free series covering model comparison, prompting, vector databases, RAG, function calling, security, agents, and fine-tuning.', url: 'https://www.youtube.com/watch?v=k7HaeJs-N-o', type: 'video', free: true, source: 'Microsoft Developer' },
    { id: 'ai-e8', title: 'LangChain Documentation', description: 'Open-source documentation for model calls, retrieval, tools, and application workflows.', url: 'https://python.langchain.com/docs/get_started/introduction', type: 'docs', free: true, source: 'LangChain' },
    { id: 'ai-e9', title: 'Microsoft Learn — Explore Generative AI', description: 'Free module covering LLMs, multimodal generation, responsible AI, and an applied exercise.', url: 'https://learn.microsoft.com/en-us/training/modules/explore-generative-ai/', type: 'docs', free: true, source: 'Microsoft Learn' },
  ],
  'ai-design': [
    { id: 'ai-d3', title: 'Figma Help Center', description: 'Official Figma guidance and product documentation for AI-assisted design workflows.', url: 'https://help.figma.com/', type: 'docs', free: true, source: 'Figma' },
    { id: 'ai-d4', title: 'Canva Design School', description: 'Free design education for composition, hierarchy, visual communication, and creative fundamentals.', url: 'https://www.canva.com/designschool/', type: 'docs', free: true, source: 'Canva' },
    { id: 'ai-d5', title: 'Microsoft — Generative AI for Beginners', description: 'Free series including image generation and UX design for AI applications.', url: 'https://www.youtube.com/watch?v=k7HaeJs-N-o', type: 'video', free: true, source: 'Microsoft Developer' },
  ],
}

export const AI_RESOURCE_STAGE_MAP: Record<string, Record<string, number>> = {
  'ai-foundations': { 'ai-f8': 1, 'ai-f9': 1, 'ai-f11': 1, 'ai-f10': 3 },
  'ai-work': { 'ai-w4': 1, 'ai-w5': 5, 'ai-w6': 5 },
  'ai-research': { 'ai-r3': 1, 'ai-r4': 3, 'ai-r5': 1 },
  'ai-content': { 'ai-c3': 1, 'ai-c4': 4, 'ai-c5': 3 },
  'ai-youtube': { 'ai-y3': 9, 'ai-y4': 10, 'ai-y5': 10, 'ai-y6': 3 },
  'ai-software-development': { 'ai-s4': 4, 'ai-s5': 5, 'ai-s6': 4, 'ai-s7': 7 },
  'ai-automation': { 'ai-a4': 2, 'ai-a5': 2, 'ai-a6': 5 },
  'ai-agents': { 'ai-ag4': 1, 'ai-ag5': 1, 'ai-ag6': 4, 'ai-ag7': 7 },
  'ai-engineering': { 'ai-e5': 1, 'ai-e6': 1, 'ai-e7': 6, 'ai-e8': 6, 'ai-e9': 2 },
  'ai-design': { 'ai-d3': 2, 'ai-d4': 1, 'ai-d5': 3 },
}

const q = (question: string, options: string[], correctIndex: number, explanation: string): QuizQuestion => ({ question, options, correctIndex, explanation })

/** Harder, application-first mastery checks. One checkpoint is inserted after each AI stage. */
export const AI_STAGE_CHECKPOINTS: Record<string, Record<number, QuizQuestion[]>> = {
  'ai-foundations': {
    1: [q('A colleague says AI outputs are factual because models are trained on internet data. What is the best correction?', ['Training makes every output factual', 'Models learn patterns and generate outputs; factual reliability still requires verification', 'AI memorizes every webpage exactly', 'Search engines guarantee AI accuracy'], 1, 'Training enables pattern learning, not a guarantee that every generated claim is true.'), q('You receive a confident answer to a high-stakes question. What should you do?', ['Trust the confidence', 'Ask the model to promise accuracy', 'Identify what needs verification and check authoritative evidence', 'Publish it if the answer sounds professional'], 2, 'Confidence and fluency are not evidence.')],
    2: [q('You need a current sourced answer about a fast-changing topic. What is the strongest approach?', ['Use any chatbot and trust its first answer', 'Use a tool suited to current research, inspect sources, and verify important claims', 'Use an older model', 'Avoid all AI'], 1, 'Tool selection should reflect freshness, evidence needs, and consequences of error.'), q('Two AI tools give different answers. What should determine your choice?', ['Which sounds more confident', 'Task requirements, source quality, reliability, latency, and cost', 'Which has the best logo', 'Which answer is longer'], 1, 'Professional tool selection is evidence- and task-driven.')],
    3: [q('Which prompt is strongest for a professional task?', ['Write something about marketing.', 'Act as an expert.', 'Define the task, context, audience, constraints, desired format, and useful examples.', 'Write a very long prompt with unrelated context.'], 2, 'Good instructions reduce ambiguity with relevant context and explicit output requirements.'), q('A prompt works in one situation but fails in another. What should you inspect first?', ['Font size', 'Context, input quality, constraints, and task definition', 'User age', 'Emoji usage'], 1, 'Prompt performance depends heavily on the information and constraints supplied.')],
    4: [q('You are deciding between two business strategies. What is the strongest role for AI?', ['Make the decision', 'Surface assumptions, alternatives, tradeoffs, and questions while you retain responsibility', 'Choose the most confident option', 'Generate a conclusion without evidence'], 1, 'AI can strengthen reasoning without becoming the accountable decision-maker.')],
    5: [q('An AI report contains three plausible statistics. What is the correct professional gate?', ['Plausibility is enough', 'Verify the statistics against authoritative sources before using them as facts', 'Ask the same model to confirm them', 'Remove all numbers'], 1, 'Important factual claims need independent evidence.')],
    6: [q('What makes an AI workflow repeatable?', ['More prompts', 'A defined task, stable inputs, explicit instructions, output criteria, review points, and iteration', 'Using one provider forever', 'Never changing anything'], 1, 'Repeatability comes from process design and evaluation.'), q('A workflow produces inconsistent results. What should you improve first?', ['Add random prompts', 'Define success criteria and test representative cases', 'Publish anyway', 'Use the longest context possible'], 1, 'Evaluation turns subjective output quality into something you can improve systematically.')],
  },
  'ai-work': {
    1: [q('Your manager needs a concise update from messy notes. What should you give the AI?', ['Only "summarize"', 'Notes plus audience, purpose, decisions/actions, and desired format', 'A demand to be perfect', 'No context'], 1, 'Relevant context and output requirements improve usefulness.'), q('Which recurring task is the strongest AI workflow candidate?', ['A one-off ambiguous decision', 'A structured weekly report with stable inputs and review criteria', 'A confidential task using an unapproved tool', 'An irreversible emergency decision'], 1, 'Repeatable, structured, reviewable tasks are strong candidates.')],
    2: [q('An AI summary of a contract contains an incorrect clause. What should happen?', ['Use it as legal advice', 'Check important clauses against the original and appropriate professional guidance', 'Publish it', 'Ask AI to sound more certain'], 1, 'AI can assist document work but should not replace consequential professional review.')],
    3: [q('Which learning workflow uses AI without replacing learning?', ['Ask for answers and memorize them', 'Ask for explanations, attempt problems yourself, request feedback, and test understanding', 'Have AI complete all exercises', 'Avoid feedback'], 1, 'Active practice and feedback produce stronger learning than passive consumption.')],
    4: [q('An AI-generated project plan has an unrealistic milestone. What should you do?', ['Accept it', 'Compare it with real capacity and dependencies, then revise the estimate', 'Delete the plan', 'Double the budget'], 1, 'AI proposes; real constraints determine the plan.')],
    5: [q('What should be defined before an organization deploys an AI workflow widely?', ['A rule that every task must use AI', 'Approved use cases, data boundaries, review requirements, and success measures', 'One prompt for everyone', 'No human review'], 1, 'Responsible adoption needs governance and measurable outcomes.')],
  },
  'ai-research': {
    1: [q('What is the strongest first use of AI in research?', ['Produce the final answer without sources', 'Expand questions, discover terminology, suggest search directions, and organize leads', 'Replace source reading', 'Decide what is true'], 1, 'AI is excellent for discovery when evidence remains a separate verification step.')],
    2: [q('AI gives you a precise statistic without a source. What is the correct next step?', ['Cite the AI', 'Verify it against an authoritative source', 'Ask AI to make it more precise', 'Assume it is correct'], 1, 'Specificity is not evidence.')],
    3: [q('Two credible sources disagree. What should you inspect?', ['Only which one ranks higher', 'Methodology, date, definitions, evidence, and context', 'Only the headline', 'Which one agrees with you'], 1, 'Conflicting evidence requires comparative analysis.')],
    4: [q('AI provides a quote attributed to a public figure. What should you do?', ['Publish it', 'Locate the original record and verify wording and context', 'Ask another AI', 'Remove quotation marks but keep the claim'], 1, 'Quotes should be verified against primary or authoritative records.')],
    5: [q('What should a professional research brief expose?', ['Only the conclusion', 'Question, evidence, uncertainty, sources, and reasoning', 'Only prompts', 'Only a bibliography'], 1, 'Decision-makers need both conclusions and the evidence behind them.')],
  },
  'ai-content': {
    1: [q('A creator wants 20 nearly identical AI posts with little original insight. What is the core problem?', ['They are too short', 'The workflow prioritizes volume without distinctive value', 'AI cannot write headlines', 'Calendars are bad'], 1, 'AI-assisted content should add genuine value rather than interchangeable mass production.')],
    2: [q('Which workflow preserves human authorship?', ['AI writes and publishes', 'Human defines angle and evidence, AI assists, human edits and verifies', 'AI chooses claims and sources without review', 'Paraphrase a competitor'], 1, 'The human owns perspective, evidence, editorial judgment, and final quality.')],
    3: [q('AI identifies claims for an article. What comes next?', ['Assume them true', 'Trace important claims to reliable sources', 'Ask another AI to rewrite them', 'Add adjectives'], 1, 'Research and verification remain necessary.')],
    4: [q('AI produces a striking visual that misrepresents a product feature. What should happen?', ['Use it', 'Reject or revise it for accuracy and user expectations', 'Hide the source', 'Add effects'], 1, 'Visual communication must remain truthful and fit the product.')],
    5: [q('A content team measures only number of posts. What is missing?', ['More tools', 'Outcome and quality measures such as audience response, retention, conversions, and accuracy', 'More prompts', 'A larger calendar'], 1, 'Output volume is not the same as effectiveness.')],
  },
  'ai-youtube': {
    1: [q('What should determine a new channel strategy?', ['Only what AI can produce cheaply', 'A specific audience, clear value proposition, sustainable pillars, and evidence of demand', 'Only the highest CPM niche', 'Competitor uploads'], 1, 'Strategy begins with audience value and sustainable differentiation.')],
    2: [q('A topic has high search demand and many competitors. What should you investigate?', ['Publish immediately', 'Search intent, competitor weaknesses, and a differentiated angle', 'Copy the leader', 'Ignore it'], 1, 'Demand alone is insufficient.')],
    3: [q('Which script workflow is strongest?', ['Generate and publish', 'Research, define promise, outline, draft, fact-check, edit, finalize', 'Generate ten scripts and publish all', 'Paraphrase a competitor'], 1, 'Professional scripts are researched, verified, and edited around a clear viewer promise.')],
    4: [q('A thumbnail gets clicks but viewers leave immediately. What is the likely issue?', ['The thumbnail is too good', 'The packaging promise may not match the opening/content', 'The audience is always wrong', 'Make the video longer'], 1, 'Packaging and delivery need to create consistent expectations.')],
    5: [q('Which approach creates the clearest current monetization risk?', ['AI brainstorming', 'AI-assisted editing', 'Repetitive mass-produced videos with little original value', 'AI captions'], 2, 'YouTube states that inauthentic mass-produced content can be ineligible for monetization.')],
    6: [q('When must realistic AI-altered content generally be disclosed?', ['Never', 'When AI meaningfully alters/generates realistic content that could mislead viewers', 'Only if a viewer asks', 'Only on Shorts'], 1, 'YouTube requires disclosure for specified realistic AI-generated or meaningfully altered content.')],
    7: [q('A video has high impressions and low CTR. What should be investigated first?', ['Packaging and audience targeting', 'Camera resolution only', 'Password security', 'Description length only'], 0, 'High impressions with low CTR points toward packaging/audience fit.')],
    8: [q('What is the purpose of retention editing?', ['Make every second chaotic', 'Remove unnecessary friction while preserving clarity, story, and expectations', 'Hide weak content', 'Increase duration'], 1, 'Retention work should improve communication and pacing.')],
    9: [q('A creator uses AI for scripts and images. What should remain human-owned?', ['Nothing', 'Audience understanding, editorial judgment, originality, fact-checking, and final quality', 'Only the upload button', 'Only the thumbnail'], 1, 'AI accelerates production; the creator remains responsible for the work.')],
    10: [q('Why should AI-assisted creators monitor current YouTube policy?', ['Policies never change', 'AI intersects with originality, reused content, inauthentic content, and disclosure requirements', 'Only large channels need policy knowledge', 'Policies only affect thumbnails'], 1, 'Platform rules are part of professional content operations.')],
  },
  'ai-software-development': {
    1: [q('What is the most dangerous misconception about generated code?', ['It can be useful', 'If it compiles, it must be correct', 'It can speed up prototypes', 'It can explain code'], 1, 'Compilation does not prove correctness, security, performance, or maintainability.')],
    2: [q('What improves AI-generated implementation most?', ['Vague requests', 'Clear requirements, constraints, interfaces, acceptance criteria, and context', 'More emojis', 'No project context'], 1, 'Specific requirements reduce ambiguity.')],
    3: [q('An AI-generated bug fix passes one test but you cannot explain the root cause. What next?', ['Ship it', 'Reproduce and understand the failure, then validate the fix against it', 'Delete the bug', 'Ask AI to sound certain'], 1, 'A professional fix requires understanding and evidence.')],
    4: [q('When should an AI coding agent be used instead of inline completion?', ['Always', 'For bounded multi-step tasks where broader context and controlled autonomy provide value', 'Never', 'Only for CSS'], 1, 'Tool autonomy should match task scope and review capacity.')],
    5: [q('An agent modifies unrelated authentication files. What should happen?', ['Merge if tests pass', 'Review the diff, revert unrelated changes, and verify requested behavior', 'Ignore it', 'Deploy immediately'], 1, 'Scope control and diff review are essential.')],
    6: [q('Why are AI-generated tests not sufficient on their own?', ['They cannot run', 'They can encode wrong assumptions or miss important behaviors', 'AI cannot write tests', 'Tests are unnecessary'], 1, 'Tests provide evidence only for what they actually cover.')],
    7: [q('Which workflow best combines AI speed with engineering discipline?', ['Generate everything then review at the end', 'Define requirements, delegate bounded tasks, inspect diffs, test, manually verify, integrate', 'Avoid tests', 'Let AI choose architecture'], 1, 'Continuous bounded review is safer and more maintainable.')],
    8: [q('What should a team document for AI-assisted coding?', ['Only the tool name', 'Acceptable uses, coding standards, review expectations, security rules, and maintainability requirements', 'Nothing', 'Only prompts'], 1, 'Teams need shared engineering controls, not merely tool access.')],
  },
  'ai-automation': {
    1: [q('Which process is the strongest automation candidate?', ['Stable, repetitive process with clear inputs and outputs', 'Ambiguous negotiation', 'Irreversible high-impact decision without review', 'Constantly changing process'], 0, 'Stable, measurable work is easier to automate safely.')],
    2: [q('Why do workflows need explicit failure paths?', ['They make diagrams prettier', 'APIs, data, credentials, and AI outputs can fail and need safe recovery', 'They guarantee no failures', 'They replace testing'], 1, 'Reliable automation assumes failure.')],
    3: [q('A workflow receives an API 401. What should you inspect?', ['Only the prompt', 'Credentials, token scope/expiry, endpoint, and request configuration', 'Only UI', 'Nothing'], 1, '401 indicates an authentication/authorization problem at the request boundary.')],
    4: [q('A webhook can change customer records. What control is appropriate?', ['Accept every payload', 'Authenticate and validate the payload and restrict allowed actions', 'Disable logs', 'Trust the URL'], 1, 'External triggers require authentication, validation, and constrained effects.')],
    5: [q('Where should AI sit inside an automation?', ['Everywhere', 'Where probabilistic language understanding adds value, surrounded by deterministic controls', 'Only at the beginning', 'Only at the end'], 1, 'AI is useful for interpretation/generation while fixed rules handle predictable operations.')],
    6: [q('Why validate structured data between steps?', ['To make it prettier', 'Malformed data can cause downstream failures or incorrect actions', 'Validation is unnecessary', 'APIs never fail'], 1, 'Validation catches bad data early.')],
    7: [q('Which action usually deserves human approval?', ['Formatting a document', 'A consequential customer refund where exceptions are possible', 'Sorting a list', 'Renaming a file'], 1, 'Consequential or ambiguous actions benefit from human oversight.')],
    8: [q('A production workflow fails periodically. What should be added?', ['Ignore it', 'Logs, alerts, bounded retries, failure handling, and safe recovery/replay', 'Infinite retries', 'More prompts only'], 1, 'Production automation needs observability and controlled recovery.')],
  },
  'ai-agents': {
    1: [q('Which description best fits an AI agent?', ['A static FAQ', 'A system pursuing a goal through model decisions and tool actions within defined boundaries', 'Any chatbot', 'A search engine'], 1, 'Agents combine model decisions with actions and boundaries.')],
    2: [q('Should every simple FAQ become an agent?', ['Yes', 'No; a direct response or deterministic workflow may be simpler and more reliable', 'Only if it is short', 'Only on mobile'], 1, 'Use the simplest reliable architecture that meets the need.')],
    3: [q('Why can deterministic workflows be preferable to agents?', ['They are always smarter', 'Known steps are easier to test, constrain, and reason about', 'They hallucinate more', 'They need no requirements'], 1, 'Predictable processes benefit from predictable execution.')],
    4: [q('What should an agent tool contract define?', ['Only a name', 'Purpose, inputs, constraints, permissions, and expected result', 'Marketing copy', 'No validation'], 1, 'Tools define the agent’s action boundary and need explicit contracts.')],
    5: [q('Why is poorly designed long-term memory risky?', ['It uses no storage', 'Stale, irrelevant, or sensitive information can influence future decisions', 'Memory always improves accuracy', 'Agents cannot use context'], 1, 'Memory introduces state that must be governed and relevant.')],
    6: [q('An agent repeatedly fails a subtask. What should it do?', ['Retry forever', 'Use bounded recovery/replanning and escalate when appropriate', 'Hide the error', 'Invent a result'], 1, 'Reliable agents need bounded recovery and escalation.')],
    7: [q('Why should tool calls be observable?', ['Decoration', 'To diagnose failures and audit consequential behavior', 'To use more tokens', 'To remove testing'], 1, 'Tool traces provide evidence of agent behavior.')],
    8: [q('Which task clearly warrants human approval?', ['Drafting a note', 'Executing an irreversible financial transaction from ambiguous evidence', 'Formatting JSON', 'Generating ideas'], 1, 'High-impact irreversible actions require strong controls.')],
    9: [q('What should an agent evaluation set contain?', ['Only easy cases', 'Representative normal cases, edge cases, failures, and safety-sensitive scenarios', 'Only developer favorites', 'No expected outcomes'], 1, 'Evaluation should reflect real use and important failure modes.')],
    10: [q('When is multi-agent coordination justified?', ['Always', 'When specialized responsibilities provide measurable value that a simpler design cannot', 'For every chatbot', 'Only for images'], 1, 'Complexity should be justified by a real requirement.')],
  },
  'ai-engineering': {
    1: [q('Your application expects structured JSON from a model. What is the strongest approach?', ['Free-form prose', 'Supported structured output/schema plus validation', 'String slicing only', 'Manual copy/paste'], 1, 'Structured output plus validation is safer for software integration.')],
    2: [q('A cheap model handles classification but fails complex reasoning. What should the architecture do?', ['Use the expensive model for everything', 'Route tasks according to capability, cost, and latency requirements', 'Hide errors', 'Avoid models'], 1, 'Model routing can balance quality, cost, and latency.')],
    3: [q('Why validate output even when a schema is used?', ['Schemas guarantee semantics', 'Values can still be wrong or unsupported', 'Validation is useless', 'Schemas make models deterministic'], 1, 'Structural validity does not guarantee semantic correctness.')],
    4: [q('What do embeddings primarily enable?', ['Exact keyword matching only', 'Numerical representations that support semantic similarity search', 'Encryption', 'Video generation'], 1, 'Embeddings support semantic retrieval.')],
    5: [q('Why does chunking matter in RAG?', ['Branding', 'Chunk boundaries affect retrieval relevance and context quality', 'It guarantees citations', 'It replaces embeddings'], 1, 'Poor chunking can make relevant evidence difficult to retrieve.')],
    6: [q('A RAG system retrieves the wrong evidence. What should you NOT do first?', ['Inspect retrieval', 'Evaluate chunking/query formulation', 'Blindly increase model temperature', 'Compare retrieved evidence with expected evidence'], 2, 'Generation settings cannot fix incorrect retrieval.')],
    7: [q('When is hybrid search useful?', ['When semantic similarity and exact lexical matches both matter', 'Only for images', 'Never', 'Only without a database'], 0, 'Hybrid retrieval can combine semantic and keyword signals.')],
    8: [q('What is a strong AI evaluation practice?', ['One impressive demo', 'Representative test cases with defined criteria and regression checks', 'Ask the model if it did well', 'Measure tokens only'], 1, 'AI quality requires repeatable evaluation.')],
    9: [q('An AI feature is accurate but expensive. What should you investigate?', ['Nothing', 'Caching, routing, context size, batching, model choice, and unnecessary calls', 'UI color', 'A more expensive model'], 1, 'Cost optimization comes from architecture and workload efficiency.')],
    10: [q('What is required before deploying an AI API?', ['A demo', 'Security, secrets management, rate limits, monitoring, evaluation, error handling, and fallback/rollback', 'A logo', 'A longer prompt'], 1, 'Production AI needs standard software controls plus AI-specific evaluation and monitoring.')],
  },
  'ai-design': {
    1: [q('What is AI especially useful for in early design?', ['Exploring many directions quickly', 'Making final decisions without users', 'Replacing accessibility checks', 'Eliminating design principles'], 0, 'AI is useful for breadth and exploration.')],
    2: [q('An AI-generated UI looks attractive but hides the primary task. What should happen?', ['Keep it', 'Revise hierarchy based on user goals and usability evidence', 'Add animation', 'Generate more versions'], 1, 'Usability outweighs novelty.')],
    3: [q('Which practice improves consistency in AI-assisted visual generation?', ['Random prompts', 'Defined visual direction, constraints, references, and reusable patterns', 'Change style each screen', 'Avoid iteration'], 1, 'Constraints and references support coherent visual language.')],
    4: [q('What is the designer responsible for when using AI-generated visuals?', ['Only choosing the prettiest result', 'Accuracy, accessibility, brand fit, originality, and user impact', 'Nothing', 'Only resizing'], 1, 'AI does not transfer design responsibility to the tool.')],
    5: [q('A stakeholder asks for a design based on an unsupported assumption about users. What should the designer do?', ['Generate it', 'Challenge the assumption and seek evidence', 'Hide it', 'Ask AI to justify it'], 1, 'Design decisions should be grounded in evidence.')],
    6: [q('Why prototype AI-assisted ideas before building the whole system?', ['Prototypes make learning cheaper before full implementation', 'AI prototypes are always final', 'It avoids research', 'It guarantees adoption'], 0, 'Prototyping reduces the cost of learning.')],
    7: [q('How should AI support a design system?', ['Invent a new style every time', 'Help apply established tokens/components while humans review consistency', 'Replace the system', 'Ignore accessibility'], 1, 'AI can accelerate application while the design system remains the source of consistency.')],
    8: [q('When should a designer reject an AI suggestion?', ['Whenever AI made it', 'When it conflicts with user needs, accessibility, evidence, ethics, or the design goal', 'Never', 'Only when ugly'], 1, 'Human judgment evaluates AI against real constraints.')],
  },
}

export const AI_PROJECT_EXTENSIONS: Record<string, Project[]> = {
  'ai-foundations': [{ id: 'ai-f-p3', title: 'AI Workflow Case Study', description: 'Choose one recurring task. Document the original process, identify where AI helps, build the workflow, test three iterations, record failures, define review criteria, and present the before/after process.', level: 'intermediate', techTags: ['AI', 'Workflow Design', 'Evaluation', 'Portfolio'] }],
  'ai-work': [{ id: 'ai-w-p4', title: 'Professional AI Workflow Portfolio', description: 'Create three documented professional workflows with task definition, context template, instructions, expected output, review checklist, failure examples, and improved final workflow.', level: 'advanced', techTags: ['AI', 'Productivity', 'Workflow Design', 'Portfolio'] }],
  'ai-research': [{ id: 'ai-r-p2', title: 'Research Audit & Evidence Map', description: 'Choose a current claim, map at least five sources, classify evidence, record conflicts, verify central claims, and deliver a brief with an evidence table and uncertainty notes.', level: 'advanced', techTags: ['Research', 'Verification', 'Source Evaluation', 'Portfolio'] }],
  'ai-content': [{ id: 'ai-c-p4', title: 'Original Content Campaign', description: 'Build a seven-day campaign from one core idea. Deliver research, editorial angle, original draft, AI-assisted revisions, fact-check log, visual direction, platform adaptations, and measurement plan.', level: 'advanced', techTags: ['AI', 'Content Strategy', 'Research', 'Portfolio'] }],
  'ai-youtube': [{ id: 'ai-y-p3', title: 'YouTube Pilot Series', description: 'Produce three related videos for one audience. Document research, differentiation, scripts, production, thumbnails, titles, AI disclosures where required, analytics review, and changes for video four.', level: 'advanced', techTags: ['AI', 'YouTube', 'Analytics', 'Production', 'Portfolio'] }],
  'ai-software-development': [{ id: 'ai-s-p4', title: 'AI Engineering Audit', description: 'Review an AI-assisted application for architecture, generated-code quality, tests, security, performance, maintainability, and prioritized remediation.', level: 'advanced', techTags: ['AI', 'Software Engineering', 'Testing', 'Security', 'Portfolio'] }],
  'ai-automation': [{ id: 'ai-a-p2', title: 'Production Automation Design', description: 'Design an automation with trigger, data contract, transformations, AI step, validation, human approval, retries, logging, failure handling, and maintenance plan.', level: 'advanced', techTags: ['AI', 'Automation', 'APIs', 'Reliability', 'Portfolio'] }],
  'ai-agents': [{ id: 'ai-ag-p2', title: 'Bounded Agent System', description: 'Build a bounded agent. Document tools, permissions, context, memory, planning, evaluation set, failure modes, human approvals, cost limits, and monitoring. Demonstrate five failure cases.', level: 'advanced', techTags: ['AI Agents', 'Tool Use', 'Evaluation', 'Safety', 'Portfolio'] }],
  'ai-engineering': [{ id: 'ai-e-p2', title: 'Production RAG Evaluation', description: 'Build a small RAG application, create an evaluation set, measure retrieval and answer quality, inspect failures, improve retrieval, monitor cost, and document tradeoffs.', level: 'advanced', techTags: ['RAG', 'Embeddings', 'Evaluation', 'AI Engineering', 'Portfolio'] }],
  'ai-design': [{ id: 'ai-d-p2', title: 'AI-Assisted Design Case Study', description: 'Complete a design problem from research to prototype. Show AI explorations, rejected alternatives, accessibility checks, user feedback, final design, and where human judgment changed the output.', level: 'advanced', techTags: ['AI', 'UI/UX', 'Design Systems', 'Research', 'Portfolio'] }],
}
