import type { AIPracticeTask } from './ai-practice'

export const AI_ADVANCED_PRACTICE_TASKS: AIPracticeTask[] = [
  { id: 'ai-content-p1', trackId: 'ai-content', stageId: 1, title: 'Practice: define the audience before generating', description: 'Turn a broad content idea into a specific audience, problem, promise, format, and success signal.', instructions: ['Choose one topic.', 'Define the audience and the problem they care about.', 'Write the content promise and how you will judge whether it worked.'], successCriteria: ['Audience is specific.', 'The content has a clear purpose.', 'Success is measurable or observable.'] },
  { id: 'ai-content-p2', trackId: 'ai-content', stageId: 2, title: 'Practice: research before drafting', description: 'Create a research brief for a piece of content before asking AI to draft it.', instructions: ['List the claims the content must support.', 'Collect credible sources.', 'Give AI only the useful context and ask it to identify gaps.'], successCriteria: ['Claims are separated from opinions.', 'Sources can be traced.', 'AI is used for synthesis rather than fabricated evidence.'] },
  { id: 'ai-content-p3', trackId: 'ai-content', stageId: 3, title: 'Practice: build and edit an AI-assisted draft', description: 'Generate a first draft, then improve it with a human editorial pass.', instructions: ['Create a brief and constraints.', 'Generate a draft.', 'Edit for accuracy, originality, structure, voice, and audience fit.'], successCriteria: ['The final version is materially better than the first draft.', 'Unsupported claims are removed or verified.', 'The final voice is appropriate for the audience.'] },
  { id: 'ai-content-p4', trackId: 'ai-content', stageId: 4, title: 'Practice: create a visual direction board', description: 'Use AI-assisted visuals to explore several directions, then choose one using explicit design criteria.', instructions: ['Define visual objectives.', 'Generate multiple directions.', 'Compare them and select one based on brand and audience constraints.'], successCriteria: ['Selection criteria are explicit.', 'The chosen direction serves communication goals.', 'You can explain why alternatives were rejected.'] },
  { id: 'ai-content-p5', trackId: 'ai-content', stageId: 5, title: 'Practice: build a repeatable content production workflow', description: 'Document a repeatable process from research through editing, quality control, and publication.', instructions: ['Map the production steps.', 'Identify where AI saves time.', 'Add editorial and factual review gates.'], successCriteria: ['The workflow is repeatable.', 'Quality controls are explicit.', 'AI does not become the final editor of truth or strategy.'] },
  { id: 'ai-youtube-p1', trackId: 'ai-youtube', stageId: 1, title: 'Practice: analyze a channel before copying its format', description: 'Study a real channel and infer its audience, promise, packaging, and content pattern.', instructions: ['Choose one successful channel.', 'Identify audience, recurring formats, hooks, titles, and thumbnails.', 'Write what you would adapt and what you would not copy.'], successCriteria: ['You identify a real audience.', 'You separate transferable principles from copying.', 'Your proposed angle is differentiated.'] },
  { id: 'ai-youtube-p2', trackId: 'ai-youtube', stageId: 2, title: 'Practice: validate a YouTube topic', description: 'Take one topic idea and test whether there is a credible audience need before scripting.', instructions: ['Generate competing topic angles.', 'Check search/discovery signals and existing competition.', 'Choose one angle and explain the decision.'], successCriteria: ['Topic choice is evidence-informed.', 'The angle is specific.', 'You can explain why viewers would care.'] },
  { id: 'ai-youtube-p3', trackId: 'ai-youtube', stageId: 3, title: 'Practice: turn research into an original script', description: 'Use AI to assist with structure and iteration while keeping the editorial idea yours.', instructions: ['Collect supporting evidence.', 'Create the hook and narrative structure.', 'Use AI for alternative phrasing, then rewrite the final script yourself.'], successCriteria: ['The script has a clear promise.', 'Important claims are supported.', 'The final script has an original editorial angle.'] },
  { id: 'ai-youtube-p4', trackId: 'ai-youtube', stageId: 4, title: 'Practice: create a production plan', description: 'Plan a video before generating assets so the tools serve the story rather than determine it.', instructions: ['Create a shot/visual list.', 'Choose voice, visuals, music, and editing needs.', 'Identify which assets require disclosure or rights checks.'], successCriteria: ['Every asset has a purpose.', 'The workflow is feasible with available tools.', 'Disclosure/rights concerns are identified.'] },
  { id: 'ai-youtube-p5', trackId: 'ai-youtube', stageId: 5, title: 'Practice: edit for retention and clarity', description: 'Take a rough cut and identify where pacing, redundancy, or unclear visuals weaken the viewer experience.', instructions: ['Watch once without editing.', 'Mark slow/unclear sections.', 'Make targeted changes and compare the revised cut.'], successCriteria: ['Edits are tied to a viewer problem.', 'The video is clearer and more purposeful.', 'You can explain the major editorial changes.'] },
  { id: 'ai-youtube-p6', trackId: 'ai-youtube', stageId: 6, title: 'Practice: evaluate packaging', description: 'Create two title/thumbnail combinations for the same video and choose one using audience and promise alignment.', instructions: ['Create two distinct packages.', 'Check whether the promise matches the actual video.', 'Choose the stronger package and explain why.'], successCriteria: ['The package is accurate.', 'The promise is clear.', 'The choice is based on audience relevance rather than clickbait alone.'] },
  { id: 'ai-youtube-p7', trackId: 'ai-youtube', stageId: 7, title: 'Practice: use analytics to form a hypothesis', description: 'Given a small set of YouTube metrics, identify one likely problem and propose the next experiment.', instructions: ['Review impressions, CTR, retention, and watch time.', 'Identify the strongest signal.', 'Propose one change and the metric that should move.'], successCriteria: ['The diagnosis is tied to the data.', 'The experiment changes one meaningful variable.', 'The success metric is explicit.'] },
  { id: 'ai-software-development-p1', trackId: 'ai-software-development', stageId: 1, title: 'Practice: decompose a coding task before prompting', description: 'Turn a feature request into smaller implementation and verification tasks before asking an AI coding tool for help.', instructions: ['Write the feature requirement.', 'Break it into components, data, behavior, and tests.', 'Only then ask AI to assist with one bounded task.'], successCriteria: ['The scope is clear.', 'Dependencies are identified.', 'The AI request is bounded.'] },
  { id: 'ai-software-development-p2', trackId: 'ai-software-development', stageId: 2, title: 'Practice: review generated code', description: 'Inspect generated code for correctness, readability, edge cases, and unnecessary complexity.', instructions: ['Generate a small implementation.', 'Explain every important line in your own words.', 'Identify one improvement or risk.'], successCriteria: ['You can explain the code.', 'You identify a real risk or improvement.', 'You do not accept code solely because it runs.'] },
  { id: 'ai-software-development-p3', trackId: 'ai-software-development', stageId: 3, title: 'Practice: debug with evidence', description: 'Use AI to help diagnose a bug while collecting logs, reproduction steps, and a minimal hypothesis.', instructions: ['Write the exact reproduction steps.', 'Gather the error and relevant code.', 'Ask AI for hypotheses and test them one by one.'], successCriteria: ['The debugging process is evidence-driven.', 'You reject hypotheses that fail testing.', 'The final fix addresses the root cause.'] },
  { id: 'ai-software-development-p4', trackId: 'ai-software-development', stageId: 4, title: 'Practice: compare AI coding tools for a task', description: 'Use two coding assistants for the same bounded feature and compare usefulness, correctness, control, and review burden.', instructions: ['Use identical requirements.', 'Review both outputs against tests and constraints.', 'Choose the better fit for the specific task.'], successCriteria: ['Comparison uses a consistent rubric.', 'Code quality is independently checked.', 'Tool choice is task-specific.'] },
  { id: 'ai-software-development-p5', trackId: 'ai-software-development', stageId: 5, title: 'Practice: constrain an agent', description: 'Write a bounded coding-agent task with explicit scope, files, acceptance criteria, and stop conditions.', instructions: ['Define exactly what the agent may change.', 'Define tests/acceptance criteria.', 'Specify what requires human approval.'], successCriteria: ['Scope is explicit.', 'The agent has clear stopping conditions.', 'Human review points are defined.'] },
  { id: 'ai-software-development-p6', trackId: 'ai-software-development', stageId: 6, title: 'Practice: test generated code', description: 'Create tests for a generated implementation and use failures to improve the implementation.', instructions: ['Identify normal and edge cases.', 'Write tests before or alongside implementation.', 'Use failures to diagnose defects.'], successCriteria: ['Tests cover meaningful behavior.', 'Failures are investigated.', 'The final code passes relevant tests.'] },
  { id: 'ai-software-development-p7', trackId: 'ai-software-development', stageId: 7, title: 'Practice: build one feature end-to-end with AI assistance', description: 'Complete one production-style feature while documenting where AI helped and where you made independent decisions.', instructions: ['Define the requirement.', 'Implement with bounded AI assistance.', 'Review, test, and document the result.'], successCriteria: ['The feature works.', 'The learner can explain the design.', 'The AI contribution did not replace engineering judgment.'] },
  { id: 'ai-automation-p1', trackId: 'ai-automation', stageId: 1, title: 'Practice: identify an automation candidate', description: 'Choose a repetitive workflow and determine whether automation will actually save time without introducing unacceptable risk.', instructions: ['Map the current manual workflow.', 'Estimate repetition and failure cost.', 'Decide whether it should be automated, partially automated, or left manual.'], successCriteria: ['The current process is explicit.', 'Trade-offs are considered.', 'Automation is justified by the problem.'] },
  { id: 'ai-automation-p2', trackId: 'ai-automation', stageId: 2, title: 'Practice: draw the workflow before building it', description: 'Design an automation workflow with inputs, transformations, outputs, errors, and human review.', instructions: ['Define the trigger.', 'Map each step and data handoff.', 'Mark failure and approval points.'], successCriteria: ['The flow is unambiguous.', 'Failure paths exist.', 'Human review is explicit where needed.'] },
  { id: 'ai-automation-p3', trackId: 'ai-automation', stageId: 3, title: 'Practice: specify an API contract', description: 'Write the inputs, outputs, authentication needs, error cases, and expected behavior for an API the workflow will use.', instructions: ['Define request and response shapes.', 'Identify authentication requirements.', 'List at least three likely failures.'], successCriteria: ['Inputs and outputs are concrete.', 'Errors are anticipated.', 'Security requirements are noted.'] },
  { id: 'ai-automation-p4', trackId: 'ai-automation', stageId: 4, title: 'Practice: design for failure', description: 'Take an automation that works on the happy path and identify what happens when inputs are missing, duplicated, malformed, or delayed.', instructions: ['List failure scenarios.', 'Define the workflow response to each.', 'Specify what should alert a human.'], successCriteria: ['Failure scenarios are realistic.', 'The workflow degrades safely.', 'Escalation rules are explicit.'] },
  { id: 'ai-agents-p1', trackId: 'ai-agents', stageId: 1, title: 'Practice: distinguish agent, workflow, and chatbot', description: 'Classify six real tasks by the amount of autonomy and tool use they actually require.', instructions: ['Describe each task.', 'Choose chatbot, deterministic workflow, or agent.', 'Explain why more autonomy would or would not add value.'], successCriteria: ['The choice matches task complexity.', 'You avoid unnecessary agents.', 'Trade-offs are explicit.'] },
  { id: 'ai-agents-p2', trackId: 'ai-agents', stageId: 4, title: 'Practice: define tool boundaries', description: 'Specify what tools an agent may call, what data each tool receives, and what the agent is forbidden from doing.', instructions: ['List the agent goal.', 'Define allowed tools and inputs.', 'Define disallowed actions and approval points.'], successCriteria: ['Tool permissions are narrow.', 'Sensitive actions require approval.', 'The boundary is understandable to another developer.'] },
  { id: 'ai-agents-p3', trackId: 'ai-agents', stageId: 7, title: 'Practice: design an agent evaluation', description: 'Create a small evaluation set for an agent workflow so you can detect regressions instead of judging one lucky run.', instructions: ['Write representative tasks.', 'Define expected behavior and failure conditions.', 'Run repeated tests and record failures.'], successCriteria: ['Tests represent realistic usage.', 'Failure modes are explicit.', 'Results can be compared over time.'] },
  { id: 'ai-engineering-p1', trackId: 'ai-engineering', stageId: 1, title: 'Practice: choose the model for the task', description: 'Compare model options using task quality, latency, cost, context requirements, and tool support rather than a generic best-model ranking.', instructions: ['Define the task and constraints.', 'Compare two current model options.', 'Choose one and explain the trade-off.'], successCriteria: ['The comparison is task-specific.', 'Cost and latency are considered.', 'Quality is evaluated on the actual task.'] },
  { id: 'ai-engineering-p2', trackId: 'ai-engineering', stageId: 2, title: 'Practice: define structured output', description: 'Design a reliable structured response for an AI application that will be consumed by software.', instructions: ['Define the fields and types.', 'Specify invalid-output behavior.', 'Create representative examples.'], successCriteria: ['The schema is explicit.', 'Failure behavior is defined.', 'Examples cover normal and edge cases.'] },
  { id: 'ai-engineering-p3', trackId: 'ai-engineering', stageId: 4, title: 'Practice: design a retrieval plan', description: 'Design a retrieval workflow for a knowledge-base application before choosing a framework.', instructions: ['Define documents and query types.', 'Choose chunking/metadata principles.', 'Define how retrieved evidence will be surfaced and checked.'], successCriteria: ['Retrieval goals are clear.', 'Evidence remains traceable.', 'The design anticipates irrelevant retrieval.'] },
  { id: 'ai-engineering-p4', trackId: 'ai-engineering', stageId: 6, title: 'Practice: create an AI evaluation set', description: 'Build a small benchmark of representative prompts and expected behaviors for an AI application.', instructions: ['Create normal, edge, and adversarial cases.', 'Define pass/fail criteria.', 'Record failures and categorize them.'], successCriteria: ['Tests reflect real use.', 'Criteria are deterministic where possible.', 'Failure categories support iteration.'] },
  { id: 'ai-design-p1', trackId: 'ai-design', stageId: 1, title: 'Practice: choose where AI helps a design workflow', description: 'Map a design project and identify which steps benefit from AI without delegating user research or design judgment.', instructions: ['Map the design process.', 'Mark good AI assistance points.', 'Mark decisions that must remain human-led.'], successCriteria: ['AI is used selectively.', 'Human judgment remains explicit.', 'The workflow is faster without weakening the design process.'] },
  { id: 'ai-design-p2', trackId: 'ai-design', stageId: 2, title: 'Practice: explore and evaluate UI directions', description: 'Generate multiple UI directions and evaluate them against user, brand, accessibility, and usability constraints.', instructions: ['Define the product and audience.', 'Generate several concepts.', 'Score them against explicit criteria and choose one.'], successCriteria: ['Criteria are explicit.', 'Selection is evidence-based.', 'The chosen design serves the user problem.'] },
  { id: 'ai-design-p3', trackId: 'ai-design', stageId: 3, title: 'Practice: refine an AI-generated visual', description: 'Take one AI-generated visual and improve composition, hierarchy, consistency, and usability rather than accepting the first output.', instructions: ['Identify three weaknesses.', 'Make targeted revisions.', 'Compare before and after against the brief.'], successCriteria: ['Revisions address real design issues.', 'The final visual better serves the brief.', 'You can explain the design decisions.'] },
]

export function getAdvancedAIPracticeTasks(trackId: string, stageId: number) {
  return AI_ADVANCED_PRACTICE_TASKS.filter((task) => task.trackId === trackId && task.stageId === stageId)
}
